name: Daily Automated Commit

on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for push access
    
    steps:
    - name: Checkout repository - 24f1001993@ds.study.iitm.ac.in
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create commit
      run: |
        echo "Automated daily update - $(date)" >> daily_log.txt
        git config --global user.name "Ayush Gupta"
        git config --global user.email "ayush9251@gmail.com"
        git add daily_log.txt
        git commit -m "Automated daily commit [$(date +'%Y-%m-%d %H:%M:%S')]"

    - name: Push changes
      run: |
        git push
